/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VisualsImport } from './routes/visuals'
import { Route as PreviousImport } from './routes/previous'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const VisualsRoute = VisualsImport.update({
  id: '/visuals',
  path: '/visuals',
  getParentRoute: () => rootRoute,
} as any)

const PreviousRoute = PreviousImport.update({
  id: '/previous',
  path: '/previous',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/previous': {
      id: '/previous'
      path: '/previous'
      fullPath: '/previous'
      preLoaderRoute: typeof PreviousImport
      parentRoute: typeof rootRoute
    }
    '/visuals': {
      id: '/visuals'
      path: '/visuals'
      fullPath: '/visuals'
      preLoaderRoute: typeof VisualsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/previous': typeof PreviousRoute
  '/visuals': typeof VisualsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/previous': typeof PreviousRoute
  '/visuals': typeof VisualsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/previous': typeof PreviousRoute
  '/visuals': typeof VisualsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/previous' | '/visuals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/previous' | '/visuals'
  id: '__root__' | '/' | '/admin' | '/previous' | '/visuals'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PreviousRoute: typeof PreviousRoute
  VisualsRoute: typeof VisualsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PreviousRoute: PreviousRoute,
  VisualsRoute: VisualsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/previous",
        "/visuals"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/previous": {
      "filePath": "previous.tsx"
    },
    "/visuals": {
      "filePath": "visuals.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
